"""
Tests for code block verification functionality with real-world repositories.

These tests verify the validation and verification of code blocks extracted
from real-world repositories.
"""

import os
import sys
import tempfile
import pytest
from pathlib import Path
import json

# Configure path correctly
project_root = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(project_root / "src"))

print(f"Python path: {sys.path}")
print(f"Current directory: {os.getcwd()}")

# Local test repository paths
RUST_ANALYZER_PATH = project_root / "test_repos" / "rust-analyzer"
REACT_PATH = project_root / "test_repos" / "react"

# Test if the repositories exist
HAS_TEST_REPOS = RUST_ANALYZER_PATH.exists() and REACT_PATH.exists()
if not HAS_TEST_REPOS:
    print(f"Warning: Test repositories not found at: {RUST_ANALYZER_PATH}, {REACT_PATH}")
    print("Some tests will be skipped")

# Import the required modules
try:
    from agent_tools.dualipa.code_extractor import (
        extract_repository,
        _verify_code_block,
        _extract_python_blocks,
        _extract_js_ts_blocks
    )
    HAS_DEPENDENCIES = True
    print("Successfully imported verification modules")
except ImportError as e:
    print(f"Import error: {e}")
    print("Required dependencies not available, tests will be skipped")
    HAS_DEPENDENCIES = False

# Skip all tests if dependencies are not available
pytestmark = pytest.mark.skipif(
    not HAS_DEPENDENCIES, 
    reason="Required modules not available"
)

def create_test_block(language, content=None, valid=True):
    """Create a test code block for verification."""
    if content is None:
        if language == "python":
            content = "def test_function():\n    return 'test'" if valid else "def test_function(:\n    return 'test'"
        elif language == "javascript":
            content = "function test() {\n    return 'test';\n}" if valid else "function test() {\n    return 'test';\n"
        elif language == "rust":
            content = "fn test() {\n    println!(\"test\");\n}" if valid else "fn test() {\n    println!(\"test\");\n"
        else:
            content = "// Sample content"
    
    return {
        "language": language,
        "content": content,
        "path": f"test.{language}",
        "start_line": 1,
        "end_line": content.count('\n') + 1,
        "type": "function",
        "name": "test_function"
    }

def test_verify_python_block():
    """Test verification of Python code blocks."""
    try:
        # Create a valid Python block
        valid_block = create_test_block("python", valid=True)
        assert _verify_code_block(valid_block), "Valid Python block should pass verification"
        
        # Create an invalid Python block
        invalid_block = create_test_block("python", valid=False)
        assert not _verify_code_block(invalid_block), "Invalid Python block should fail verification"
        
        print("Python block verification works correctly")
    except Exception as e:
        pytest.skip(f"Error in test_verify_python_block: {e}")

def test_verify_javascript_block():
    """Test verification of JavaScript code blocks."""
    try:
        # Create a valid JavaScript block
        valid_block = create_test_block("javascript", valid=True)
        assert _verify_code_block(valid_block), "Valid JavaScript block should pass verification"
        
        # Create an invalid JavaScript block (missing closing brace)
        invalid_block = create_test_block("javascript", valid=False)
        assert not _verify_code_block(invalid_block), "Invalid JavaScript block should fail verification"
        
        print("JavaScript block verification works correctly")
    except Exception as e:
        pytest.skip(f"Error in test_verify_javascript_block: {e}")

def test_verify_blocks_from_extraction():
    """Test verification of blocks generated by the extraction process."""
    try:
        # Create a temporary Python file
        with tempfile.NamedTemporaryFile(suffix='.py', mode='w') as f:
            f.write("""
def test_function():
    return "test"

class TestClass:
    def __init__(self):
        self.value = 42
    
    def get_value(self):
        return self.value
""")
            f.flush()
            
            # Set up output directory
            with tempfile.TemporaryDirectory() as temp_dir:
                output_dir = Path(temp_dir)
                
                # Extract code blocks
                with open(f.name, 'r') as file:
                    content = file.read()
                
                stats = {"code_blocks": 0}
                _extract_python_blocks(Path(f.name), content, output_dir, stats)
                
                # Verify blocks were extracted
                assert stats["code_blocks"] > 0, "Should extract at least one code block"
                print(f"Extracted {stats['code_blocks']} blocks from test file")
                
                # Get the block files
                blocks_dir = output_dir / "blocks" / "code" / "python"
                block_files = list(blocks_dir.glob("*.py"))
                assert len(block_files) > 0, "Should create at least one block file"
                
                # Verify each block
                verified_count = 0
                for block_file in block_files:
                    with open(block_file, 'r') as bf:
                        block_content = bf.read()
                    
                    block = {
                        "language": "python",
                        "content": block_content,
                        "path": str(block_file),
                        "type": "function",
                        "name": block_file.stem
                    }
                    
                    verified = _verify_code_block(block)
                    print(f"Block {block_file.name}: {'Verified' if verified else 'Failed verification'}")
                    if verified:
                        verified_count += 1
                
                assert verified_count > 0, "At least one block should pass verification"
                print(f"{verified_count}/{len(block_files)} blocks passed verification")
    except Exception as e:
        pytest.skip(f"Error in test_verify_blocks_from_extraction: {e}")

def test_verify_multifile_extraction():
    """Test verification of blocks from multiple files of different languages."""
    try:
        # Skip if test repos are not available for real-world files
        if not HAS_TEST_REPOS:
            # Create temporary files with different languages
            py_content = """
def hello_world():
    print("Hello, World!")
"""
            js_content = """
function helloWorld() {
    console.log("Hello, World!");
}
"""
            # Set up temporary files
            with tempfile.TemporaryDirectory() as input_dir:
                files = {
                    "test.py": py_content,
                    "test.js": js_content
                }
                
                file_paths = []
                for name, content in files.items():
                    file_path = Path(input_dir) / name
                    with open(file_path, 'w') as f:
                        f.write(content)
                    file_paths.append(file_path)
                
                # Set up output directory
                with tempfile.TemporaryDirectory() as output_dir:
                    # Extract blocks from each file
                    for file_path in file_paths:
                        stats = extract_repository(
                            source=str(file_path),
                            output_path=output_dir,
                            extract_documentation=False,
                            extract_code=True,
                            extract_blocks=True
                        )
                        
                        print(f"Extracted {stats.get('code_blocks', 0)} blocks from {file_path.name}")
                    
                    # Verify blocks from each language
                    for lang in ["python", "javascript"]:
                        blocks_dir = Path(output_dir) / "blocks" / "code" / lang
                        if blocks_dir.exists():
                            block_files = list(blocks_dir.glob(f"*.{lang.lower()[:2]}*"))
                            
                            for block_file in block_files:
                                with open(block_file, 'r') as bf:
                                    block_content = bf.read()
                                
                                block = {
                                    "language": lang,
                                    "content": block_content,
                                    "path": str(block_file),
                                    "type": "function",
                                    "name": block_file.stem
                                }
                                
                                verified = _verify_code_block(block)
                                print(f"{lang} block {block_file.name}: {'Verified' if verified else 'Failed verification'}")
                                assert verified, f"Block {block_file.name} should pass verification"
        else:
            # Use real repositories
            # Find files of different languages
            python_files = list(RUST_ANALYZER_PATH.glob("**/*.py"))
            js_files = list(REACT_PATH.glob("**/*.js"))
            
            # Collect files to test
            test_files = []
            if python_files:
                test_files.append(("python", python_files[0]))
            if js_files:
                test_files.append(("javascript", js_files[0]))
            
            if not test_files:
                pytest.skip("No suitable test files found in repositories")
            
            # Set up output directory
            with tempfile.TemporaryDirectory() as temp_dir:
                output_dir = Path(temp_dir)
                
                # Extract blocks from each file type
                for lang, file_path in test_files:
                    print(f"Testing extraction from {lang} file: {file_path}")
                    
                    # Extract blocks from this specific file
                    stats = extract_repository(
                        source=str(file_path),
                        output_path=temp_dir,
                        extract_documentation=False,
                        extract_code=True,
                        extract_blocks=True
                    )
                    
                    print(f"Extracted {stats.get('code_blocks', 0)} blocks from {lang} file")
                
                # Verify blocks from each language
                verified_blocks = 0
                total_blocks = 0
                
                for lang, _ in test_files:
                    blocks_dir = Path(output_dir) / "blocks" / "code" / lang
                    if blocks_dir.exists():
                        ext = ".py" if lang == "python" else ".js"
                        block_files = list(blocks_dir.glob(f"*{ext}"))
                        
                        for block_file in block_files:
                            total_blocks += 1
                            with open(block_file, 'r') as bf:
                                block_content = bf.read()
                            
                            block = {
                                "language": lang,
                                "content": block_content,
                                "path": str(block_file),
                                "type": "function",
                                "name": block_file.stem
                            }
                            
                            verified = _verify_code_block(block)
                            print(f"{lang} block {block_file.name}: {'Verified' if verified else 'Failed verification'}")
                            if verified:
                                verified_blocks += 1
                
                assert verified_blocks > 0, "At least one block should pass verification"
                print(f"{verified_blocks}/{total_blocks} blocks passed verification")
    
    except Exception as e:
        pytest.skip(f"Error in test_verify_multifile_extraction: {e}")

if __name__ == "__main__":
    pytest.main(["-xvs", __file__]) 